app:
  name: "@project.artifactId@"
  version: "@project.version@"

logging:
  level:
    ROOT: INFO
    org.springframework: TRACE
    org.boip.demo: INFO

server:
  servlet:
    context-path: "/demo"

# for actuator endpoints (spring boot 2)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      external-file: "/var/log/demo/demo.log"
