spring:
  security:
    user:
      name: "local-user"
      password: "welcome1"
  profiles:
    include:
      - "default"
  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;MODE=DB2"
    username: "sa"
    password: "sa"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
  liquibase:
    change-log: "classpath:liquibase/liquibase-changelog.xml"
    contexts: "local"

logging:
  level:
    org.boip.demo: DEBUG

server:
  port: 9090

management:
  endpoint:
    logfile:
      external-file: "logs/demo.log"

